### ISSUE TITLE
Object Detection Weights

### ISSUE THREAD

**Issue by nathanEARTH** [HaonanGuo/Remote-Sensing-ChatGPT-Human-Interactive-Remote-Sensing-Task-Solving-with-ChatGPT#1]
Hi - this is awesome. It looks like the object detection weights on GDrive are from HRNet. Is that intentional, or should these be yolov5?

**Comment by HaonanGuo** [comment]
We are sorry for the mistakes, and also thanks for your attention on RS ChatGPT. We have thoroughly updated the whole project. Looking forward to your further advice!
