### ISSUE TITLE
openai-key

### ISSUE THREAD

**Issue by Lzqbalabala** [HaonanGuo/Remote-Sensing-ChatGPT-Human-Interactive-Remote-Sensing-Task-Solving-with-ChatGPT#3]
root@autodl-container-7e0c4db22a-9f3ec4ab:~/RSGPT# python interface.py
usage: interface.py [-h] [--load LOAD] openai-key
interface.py: error: the following arguments are required: openai-key
root@autodl-container-7e0c4db22a-9f3ec4ab:~/RSGPT# python rs_chatgpt.py
usage: rs_chatgpt.py [-h] [--image-dir IMAGE_DIR] [--gpt_name {gpt-3.5-turbo,gpt-4}] [--load LOAD] openai-key
rs_chatgpt.py: error: the following arguments are required: openai-key
作者，对您的研究非常感兴趣，想问下您运行过程中出现的openai-key报错要怎么解决呢？谢谢啦

**Comment by gulabpatel** [comment]
@Lzqbalabala, In the code file, re_chatgpt.py, line 584, you need to change openai-key -> openai_key, it would then work.
also in the requirements.txt file, you need to make one change skimage -> scikit-image. and then you will have to download weights individually, create a checkpoints folder in your working directory, and upload the weights. Now good to go...
![image](https://github.com/HaonanGuo/Remote-Sensing-ChatGPT/assets/62597299/5fc05714-ec62-4ffc-855e-5d32b2388828)

**Comment by HaonanGuo** [comment]
> root@autodl-container-7e0c4db22a-9f3ec4ab:~/RSGPT# python interface.py usage: interface.py [-h] [--load LOAD] openai-key interface.py: error: the following arguments are required: openai-key root@autodl-container-7e0c4db22a-9f3ec4ab:~/RSGPT# python rs_chatgpt.py usage: rs_chatgpt.py [-h] [--image-dir IMAGE_DIR] [--gpt_name {gpt-3.5-turbo,gpt-4}] [--load LOAD] openai-key rs_chatgpt.py: error: the following arguments are required: openai-key 作者，对您的研究非常感兴趣，想问下您运行过程中出现的openai-key报错要怎么解决呢？谢谢啦

Thanks for your question. Since the project was developed initially using Pycharm, it seems that there will be some problems when running in the shell. I have thoroughly updated the whole project. Please let me know if there are any further problems. Thanks!

**Comment by HaonanGuo** [comment]
> @Lzqbalabala, In the code file, re_chatgpt.py, line 584, you need to change openai-key -> openai_key, it would then work. also in the requirements.txt file, you need to make one change skimage -> scikit-image. and then you will have to download weights individually, create a checkpoints folder in your working directory, and upload the weights. Now good to go... ![image](https://private-user-images.githubusercontent.com/62597299/298819192-5fc05714-ec62-4ffc-855e-5d32b2388828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Nzk3MTQsIm5iZiI6MTcwNjU3OTQxNCwicGF0aCI6Ii82MjU5NzI5OS8yOTg4MTkxOTItNWZjMDU3MTQtZWM2Mi00ZmZjLTg1NWUtNWQzMmIyMzg4ODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAxNTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTMxZDg4YTkzMmMxMDI0NjM5OTViYTVjODlmMzkzMmVmNTFiZWRkYWJjYTEzY2MwNWYwZjMwN2I4ZjAzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWI4hMhiIDCQyn0-q_dXfJhi-UFWDbA14ztFn2vY4TY)

Thank you very much for your contribution to the project! I have updated the whole project to increase readability (also with your solusion).
