### ISSUE TITLE
model weights (checkpoints folder)

### ISSUE THREAD

**Issue by gulabpatel** [HaonanGuo/Remote-Sensing-ChatGPT-Human-Interactive-Remote-Sensing-Task-Solving-with-ChatGPT#4]
I think it would be great if all the required weights get downloaded when running for the very first time. Downloading weights individually feels boring.

**Comment by BOUTAYEBAnasse** [comment]
it works for you ??

**Comment by HaonanGuo** [comment]
Thank you very much for the helpful suggestion. I will upload the models to HuggingFace recently. Since it is not available in my region, it leads to some bugs. I will try my best to fix them.

**Comment by gulabpatel** [comment]
Hi HaonanGuo,

Hope you are doing well!

I am interested to contribute in your project (
https://github.com/HaonanGuo/Remote-Sensing-ChatGPT). But I would request
you to share some study materials & research papers that you followed. I am
exploring from my end but any support from you would be appreciated.

Once I am clear with the basic requirements, will start discussing it
with you soon.
I look forward to hearing from you.

*Thank you & Regards,*
*Gulab Patel*


*Cell# 7388641709.*
